### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by rerb** [kristianmandrup/slush-reframe#1]
Getting error on initial run of `slush reframe` after installation.

```
$ slush reframe

/usr/local/lib/node_modules/slush-reframe/slushfile.js:20
let tasks = {};
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/slush/bin/slush.js:90:3)
    at Liftoff.launch (/usr/local/lib/node_modules/slush/node_modules/liftoff/index.js:153:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/slush/bin/slush.js:57:5)
    at Module._compile (module.js:456:26)
```

OS X 10.11.3

**Comment by kristianmandrup** [comment]
Oh? I forgot I even made this generator. I make so many and keep changing tech!
I will look into it ASAP. Looks like it needs to be compiled in ES6 mode :p
